#include <cstdio>
#include <cstdlib>
#include <string>
#include <set>
#include <map>
#include "../mediation/csv.h"

/* management address assignment report.
   the mgmt plane is 10.20.0.0/16, has been since the 2009 build.
   assignments live in devices.csv, everything else (routing-tables/,
   firewall-rules/, dns-zones/, snmp-polling.conf) is generated by hand from
   this file and then edited in place, so they drift. */

static unsigned long ip_to_u32(const std::string &ip) {
  unsigned a = 0, b = 0, c = 0, d = 0;
  sscanf(ip.c_str(), "%u.%u.%u.%u", &a, &b, &c, &d);
  return (a << 24) | (b << 16) | (c << 8) | d;
}

int main(int argc, char **argv) {
  std::string devices = "network/devices.csv";
  for (int i = 1; i < argc; i++) {
    std::string a = argv[i];
    if (a == "--devices" && i + 1 < argc) devices = argv[++i];
  }
  std::vector<Row> rows = read_csv(devices);
  if (rows.empty()) {
    fprintf(stderr, "no device file at %s\n", devices.c_str());
    return 1;
  }
  std::map<std::string, int> per_third_octet;
  std::set<std::string> seen;
  int dupes = 0, reserved = 0;
  for (size_t i = 0; i < rows.size(); i++) {
    Row r = rows[i];
    std::string ip = r["mgmt_ip"];
    if (seen.count(ip)) { printf("DUPLICATE %s %s\n", ip.c_str(), r["device_name"].c_str()); dupes++; }
    seen.insert(ip);
    unsigned long u = ip_to_u32(ip);
    char oct[16];
    snprintf(oct, sizeof(oct), "10.20.%lu.0/24", (u >> 8) & 0xff);
    per_third_octet[oct]++;
    if (((u >> 8) & 0xff) == 250) reserved++;
  }
  printf("supernet 10.20.0.0/16\n");
  printf("devices %d, addresses in use %d, internal duplicates %d\n",
         (int)rows.size(), (int)seen.size(), dupes);
  printf("addresses inside reserved 10.20.250.0/24: %d\n", reserved);
  for (std::map<std::string, int>::iterator it = per_third_octet.begin();
       it != per_third_octet.end(); ++it) {
    printf("  %-18s %d\n", it->first.c_str(), it->second);
  }
  return 0;
}
